### ISSUE TITLE
Specify @Serializer/Group for @Discriminator field 

### ISSUE THREAD

**Issue by thaonx** [schmittjoh/JMSSerializerBundle#506]
This is a example code. How to add "type" filed into a specific group ?

```
<?php
namespace Entity;
use JMS\Serializer\Annotation as JMS;
/**
 * @JMS\Discriminator(field = "type", map = {
 *    "user": "Entity\User",
 *    "mod": "Entity\Moderator"
 * })
 */
abstract class AbstractUser
{
  /**
   * @JMS\Type("integer")
   */
  public $id;
  /**
   * @JMS\Type("string")
   */
  public $name;
  /**
   * @JMS\Type("string")
   */
  public $type;
}
```

**Comment by lordelph** [comment]
I've just run into a similar issue - if I'm using groups, then the discriminator will not appear in the serialized data. 

I found that if my serialization context contained 'Default', then the discriminator will appear. So, one workaround is to ensure that all fields either have groups or are excluded, and always serialized with a context of Default + whatever groups you want.

It would be nice if there was a way to specify which groups the discriminator should appear in.

**Comment by VBelozyorov** [comment]
Same here. Thank you @lordelph for the workaround.

**Comment by goetas** [comment]
solved with https://github.com/schmittjoh/serializer/pull/579, will be included in v1.5

**Comment by patie** [comment]
@goetas i think this is not solved, im using newest version and i have same issue

**Comment by goetas** [comment]
@patie can you submit a failing test case?
